# Generated by Django 5.0 on 2023-12-20 00:33

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('products', '0002_product_product_description_and_more'), ('products', '0003_alter_product_price_and_more'), ('products', '0004_cake_product_product_ingredients')]

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default-product.png', upload_to=products.models.path_to_rename),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('cake_topping', models.CharField()),
            ],
            options={
                'verbose_name': 'cake',
                'verbose_name_plural': 'cakes',
                'ordering': ['-id'],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
