# Generated by Django 5.0 on 2023-12-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('products', '0005_cupcake_ginger_marshmallow_trifle_cake_product_type'), ('products', '0006_alter_cake_cake_topping_alter_trifle_trifle_topping')]

    dependencies = [
        ('products', '0002_product_product_description_and_more_squashed_0004_cake_product_product_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('product_type', models.CharField(blank=True, choices=[('1', 'CAKE'), ('2', 'MARSHMALLOW'), ('3', 'TRIFLE'), ('4', 'GINGER'), ('5', 'CUPCAKE')], default='5', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'cupcake',
                'verbose_name_plural': 'cupcakes',
                'ordering': ['-id'],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Ginger',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('product_type', models.CharField(blank=True, choices=[('1', 'CAKE'), ('2', 'MARSHMALLOW'), ('3', 'TRIFLE'), ('4', 'GINGER'), ('5', 'CUPCAKE')], default='4', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'ginger',
                'verbose_name_plural': 'gingers',
                'ordering': ['-id'],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Marshmallow',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('product_type', models.CharField(blank=True, choices=[('1', 'CAKE'), ('2', 'MARSHMALLOW'), ('3', 'TRIFLE'), ('4', 'GINGER'), ('5', 'CUPCAKE')], default='2', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'marshmallow',
                'verbose_name_plural': 'marshmallows',
                'ordering': ['-id'],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='cake',
            name='product_type',
            field=models.CharField(blank=True, choices=[('1', 'CAKE'), ('2', 'MARSHMALLOW'), ('3', 'TRIFLE'), ('4', 'GINGER'), ('5', 'CUPCAKE')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='cake_topping',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trifle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('trifle_topping', models.CharField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('1', 'CAKE'), ('2', 'MARSHMALLOW'), ('3', 'TRIFLE'), ('4', 'GINGER'), ('5', 'CUPCAKE')], default='3', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'trifle',
                'verbose_name_plural': 'trifles',
                'ordering': ['-id'],
            },
            bases=('products.product',),
        ),
    ]
