# Generated by Django 5.0 on 2023-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cupcake_ginger_marshmallow_trifle_cake_product_type_squashed_0006_alter_cake_cake_topping_alter_trifle_trifle_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
